---
- name: Setup Docker
  hosts: all
  roles:
    - angstwad.docker_ubuntu
  become: Yes

- name: Setup NodeJS
  hosts: all
  tasks:
    - name: download nodejs
      shell: curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
    - apt: name=nodejs
      become: yes
    # - name: symbolic links
    #   shell: ln -s /usr/bin/nodejs /usr/bin/node
    #   become: yes
